_wandb:
    value:
        cli_version: 0.19.7
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 5
                - 53
                - 55
            "2":
                - 5
                - 53
                - 55
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.7
            "8":
                - 5
            "12": 0.19.7
            "13": linux-x86_64
maxSize:
    value:
        - 50
        - 50
minNeighbors:
    value: 4
minSize:
    value:
        - 25
        - 25
n_clusters:
    value: 2
scaleFactor:
    value: 1.05
